### ISSUE TITLE
(1.18.2) Banning an item doesn't prevent getting it from trading

### ISSUE THREAD

**Issue by ricchix** [pitbox46/ItemBlacklist#5]
https://user-images.githubusercontent.com/89796563/179367465-a46cc1b6-341c-460e-841c-447327d55358.mp4

**Comment by X-Niter** [comment]
@pitbox46 I have dabbled with this in 1.16.5 which also has the bug, I've been seeing if there might be an overall global way to check for ANY banned items going to the player's inventory and if any of the banned items to go into a players inventory ever then it removes it "poof". 
I figured if we can listen to the whole inventory then we wouldn't have to make small patches to specific events. "Less code?"
Currently no successes to share due to a distraction from another project of mine.

If I get more around to this before you do, I'll make sure to share with you!

**Comment by pitbox46** [comment]
@X-Niter When I first made this mod, it was kinda a quick fix. I might look into rewriting some of it so it works better overall.

**Comment by X-Niter** [comment]
Jolly! I do think that how all things start? specific to a target goal and then it becomes much more. haha.
I'm onbaord with what you're saying, I'll keep tabs and take what you said into count when testing things out.

**Comment by pitbox46** [comment]
Resolved in latest patch. 

@X-Niter I figured out I can't really rewrite the code in the ways I would like to. I'll probably just leave it mostly as is since it works at the moment.

**Comment by X-Niter** [comment]
> Resolved in latest patch.
> 
> @X-Niter I figured out I can't really rewrite the code in the ways I would like to. I'll probably just leave it mostly as is since it works at the moment.

Roger that chief, I understand completely, I was actually semi somewhere with the idea, but was coming to a few uh... Mind road blocks could we call it? I'll move over into your discord though sense I found it. :) Msg me when ever you feel like it.
